auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “yy's Blog”
title: yy's blog
description: note && blog.
url: https://miss-fox.github.io/
feed: /atom.xml
author_info: <a href="https://miss-fox.github.io/">yy</a>
